# [START runtime]
runtime: python27
threadsafe: true
api_version: 1
# [END runtime]

handlers:
#- url: /(.+)
#  static_files: dist/\1
#  upload: dist/(.*)

# redirect the resource files
- url: /(.*\.(json|css|eot|gz|html|ico|js|map|png|jpg|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: dist/(.*)


- url: /(.*i18n.*\.json)
  static_files: dist/\1
  upload: dist/(.*)

# redirect all the path to index
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html

- url: /index.html
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

# Letsencrypt ssl
# - url: /.well-known/acme-challenge/DDsF2Ok0tEwEaNGAKrtdTwY2z9X5iG0uZstsOXyqxuQ
#  static_files: dist/acme-challenge
#  upload: dist/acme-challenge

- url: /
  static_dir: dist
  secure: always

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
  - ^(?!dist)
#skip_files:
#- ^(?!dist)
#- ^node_modules$
#- ^app\.yaml
#- ^README\..*
#- \.gitignore
#- ^\.git$
#- ^grunt\.js
#- ^src$
#- ^e2e$
#- \.editorconfig
#- ^karma\.config\.js
#- ^package\.json
#- ^protractor\.conf\.js
#- ^tslint\.json